// Edit bookmarks here - only this file.
// name/icon are optional; without them the page falls back to auto-fetching.
const CONFIG = [
  { name: "工作", links: [
    { url: "https://www.feishu.cn/", name: "飞书", icon: "https://www.feishu.cn/favicon.ico" },
    { url: "https://docs.qq.com/", name: "腾讯文档", icon: "https://docs.idqqimg.com/tim/docs/desktop/favicon.ico" },
    { url: "https://www.zhipin.com/", name: "BOSS直聘" },
    { url: "https://www.zhaopin.com/", name: "智联招聘", icon: "https://common-bucket.zhaopin.cn/img/zhilian-ico/zhilian-ico-1.0.0.png" },
  ]},
  { name: "AI", links: [
    { url: "https://chat.deepseek.com/", name: "DeepSeek", icon: "https://fe-static.deepseek.com/chat/favicon.svg" },
    { url: "https://www.doubao.com/chat/30171912988103170", name: "豆包", icon: "https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/favicon/new-doubao/64x64.png" },
    { url: "https://chatgpt.com/", name: "ChatGPT", icon: "https://chatgpt.com/cdn/assets/favicon-l4nq08hd.svg" },
    { url: "https://gemini.google.com/app", name: "Gemini", icon: "https://www.gstatic.com/lamda/images/gemini_sparkle_aurora_33f86dc0c0257da337c63.svg" },
    { url: "https://labs.google/fx/tools/flow", name: "Google Flow", icon: "https://labs.google/fx/icons/favicon/flow_favicon_w.png" },
    { url: "https://labs.google/", name: "Google Labs", icon: "https://labs.google/assets/icons/favicon-32x32.png" },
    { url: "https://copilot.microsoft.com/", name: "Copilot", icon: "https://copilot.microsoft.com/static/cmc/favicon.svg" },
    { url: "https://claude.ai/", name: "Claude" },
    { url: "https://duck.ai/", name: "Duck.ai", icon: "https://duck.ai/favicon.svg" },
    { url: "https://civitai.com/", name: "Civitai", icon: "https://civitai.com/favicon-blue.ico" },
    { url: "https://civitai.red/", name: "Civitai Ded", icon: "https://civitai.red/favicon-red.ico" },
    { url: "https://huggingface.co/", name: "Hugging Face" },
    { url: "https://gabriel.devenyi.ca/huggingface-estimate/", name: "GGUF 内存估算器", icon: "https://gabriel.devenyi.ca/huggingface-estimate/logo.svg" },
  ]},
  { name: "AI API", links: [
    { url: "https://bigmodel.cn/", name: "智谱AI", icon: "https://static.bigmodel.cn/wd-paas-front/static/images/favicon.png" },
    { url: "https://platform.deepseek.com/usage", name: "DeepSeek", icon: "https://fe-static.deepseek.com/platform/favicon.svg" },
    { url: "https://openrouter.ai/", name: "OpenRouter", icon: "https://openrouter.ai/favicon.ico" },
    { url: "https://minimaxi.com/", name: "MiniMax" },
    { url: "https://www.tavily.com/", name: "Tavily" },
  ]},
  { name: "AI 视频", links: [
    { url: "https://video.jurilu.com/", name: "巨日禄" },
    { url: "https://ai.lfxqai.com/videos", name: "Star AI", icon: "https://ai.lfxqai.com/icon.png?icon.09e865ea.png" },
    { url: "https://nova.shanhaix.com/", name: "Nova·Ai" },
    { url: "https://www.woaiduanju.com/", name: "书生梦工厂" },
    { url: "https://jimeng.jianying.com/ai-tool/generate?workspace=0", name: "即梦AI", icon: "https://lf3-lv-buz.vlabstatic.com/obj/image-lvweb-buz/common/images/dreamina-v5.ico" },
    { url: "https://www.vidu.cn/home/recommend", name: "Vidu AI", icon: "https://www.vidu.cn/logo.svg" },
    { url: "https://www.liblib.tv/", name: "LibTV" },
    { url: "https://www.liblib.art/", name: "LiblibAI" },
    { url: "https://story.neodomain.cn/home", name: "Neowow", icon: "https://story.neodomain.cn/logo.svg" },
    { url: "https://xyq.jianying.com/", name: "小云雀", icon: "https://p26-piu.byteimg.com/tos-cn-i-8jisjyls3a/6c764ca8350d46218d462fe23ea42072~tplv-8jisjyls3a-3:0:0:q75.png" },
    { url: "https://klingai.com/app", name: "可灵 AI", icon: "https://klingai.com/favicon.ico" },
    { url: "http://49.233.78.71:17861/", name: "IndexTTS Demo" },
    { url: "https://voiceailabs.com/zh", name: "Voice AI Labs" },
    { url: "https://www.ttson.cn/", name: "TTS-Online" },
  ]},
  { name: "游戏", links: [
    { url: "https://game.maj-soul.com/1/", name: "雀魂麻将", icon: "https://game.maj-soul.com/1/favicon.ico" },
    { url: "https://docs.qq.com/sheet/DT29ia2hSWUN2aU9u?tab=ksihjy", name: "岛屿计划", icon: "https://docs.gtimg.com/docs-design-resources/document-management/tencent-docs/favicon/application-vnd.tdocs-apps.sheet.png" },
    { url: "https://www.pxb7.com/", name: "螃蟹账号" },
    { url: "https://store.epicgames.com/zh-CN/", name: "Epic Games", icon: "https://static-assets-prod.epicgames.com/epic-store/static/favicon.ico" },
    { url: "https://store.steampowered.com/", name: "Steam" },
    { url: "https://store.steampowered.com/account/remotestorage", name: "Steam 云" },
    { url: "https://www.protondb.com/", name: "ProtonDB" },
    { url: "https://steamdb.info/", name: "SteamDB", icon: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cstyle%3E path %7B fill: %23000; %7D @media (prefers-color-scheme: dark) %7B path %7B fill: %23FFF; %7D %7D %3C/style%3E%3Cpath d='M7.982 0C3.807 0 .383 1.49.015 3.393l4.446.842c.36-.107.777-.164 1.198-.167l2.09-1.252c-.024-.313.168-.632.589-.905.597-.387 1.534-.598 2.487-.606a5.662 5.662 0 011.876.274c1.396.47 1.717 1.387.71 2.038-.637.413-1.659.624-2.677.604l-2.752.981c-.024.196-.165.39-.428.56-.739.48-2.177.588-3.202.243-.453-.152-.751-.37-.879-.606L.316 4.802c.287.448.749.86 1.348 1.22C.62 6.621 0 7.373 0 8.188c0 .8.598 1.538 1.606 2.131C.597 10.914 0 11.655 0 12.456 0 14.413 3.579 16 7.998 16 12.417 16 16 14.413 16 12.456c0-.8-.598-1.542-1.607-2.136C15.402 9.727 16 8.989 16 8.19c0-.82-.628-1.577-1.68-2.178 1.042-.63 1.664-1.42 1.664-2.279C15.984 1.671 12.401 0 7.982 0zm2.856 1.774c-.644.013-1.273.146-1.681.41-.688.445-.476 1.06.478 1.382.954.32 2.269.22 2.956-.226.688-.445.476-1.058-.478-1.379a3.971 3.971 0 00-1.275-.187zm.036.213c.92 0 1.663.349 1.663.778 0 .428-.744.775-1.663.775-.92 0-1.662-.347-1.662-.775 0-.429.743-.778 1.662-.778zM5.659 4.3c-.198.014-.393.02-.578.052l1.138.214a1.345.628 0 11-1.011 1.162l-1.107-.21c.125.113.305.216.543.296.803.27 1.92.186 2.5-.19.58-.374.398-.893-.406-1.164A3.38 3.38 0 005.66 4.3zm7.967 2.08v1.16c0 1.377-2.52 2.49-5.628 2.49S2.374 8.917 2.374 7.54V6.394c1.443.663 3.422 1.073 5.608 1.073 2.202 0 4.197-.416 5.644-1.088zm0 4.328v1.099c0 1.376-2.52 2.49-5.628 2.49s-5.624-1.114-5.624-2.49v-1.098c1.444.633 3.43 1.024 5.624 1.024 2.194 0 4.182-.391 5.628-1.025z'/%3E%3C/svg%3E%0A" },
    { url: "https://www.gamer520.com/", name: "Switch520", icon: "https://v1.imagehub.cc/images/2026/04/21/1210e985ce56b56f20e06094f6817d28.png" },
    { url: "https://docs.sillytavern.app/", name: "SillyTavern" },
  ]},
  { name: "系统", links: [
    { url: "https://dvel.me/posts/rime-ice/", name: "雾凇拼音", icon: "https://dvel.me/favicon-32x32.png" },
    { url: "https://lemmy.dbzer0.com/c/GenP", name: "GenP" },
    { url: "https://store.rg-adguard.net/", name: "Microsoft Store" },
    { url: "https://www.catalog.update.microsoft.com/Home.aspx", name: "Microsoft Update Catalog" },
    { url: "https://www.portablefreeware.com/", name: "Portable", icon: "https://www.portablefreeware.com/images/favicon.png" },
    { url: "https://www.powershellgallery.com/", name: "PowerShell Gallery" },
    { url: "https://scoop.sh/", name: "Scoop" },
    { url: "https://learn.microsoft.com/zh-cn/sysinternals/", name: "Sysinternals" },
    { url: "https://zhuanlan.zhihu.com/p/429496671", name: "Win10/11下WIFI无法自动/主动连接的解决方法 - 知乎", icon: "https://static.zhihu.com/heifetz/favicon.ico" },
    { url: "https://www.runoob.com/w3cnote/windows-finds-port-usage.html", name: "Windows下如何查看某个端口被谁占用 | 菜鸟教程", icon: "https://static.char123.com/images/favicon.ico" },
    { url: "https://download.schenker-tech.de/package/xmg-core-16-l23-xco16l23/", name: "XMG CORE 16 (L23)" },
    { url: "https://wiki.lineageos.org/devices/kebab/", name: "LineageOS", icon: "https://wiki.lineageos.org/images/favicons/favicon-32x32.png" },
    { url: "https://www.archlinuxcn.org/", name: "Arch Linux", icon: "https://www.archlinuxcn.org/wp-content/themes/askin2010/images/favicon.ico" },
    { url: "https://flathub.org/", name: "Flathub", icon: "https://dl.flathub.org/assets/_next/public/favicon.svg" },
    { url: "https://wiki.archlinux.org/title/V4l2loopback", name: "v4l2环回 - ArchWiki" },
  ]},
  { name: "网盘", links: [
    { url: "https://www.123pan.com/", name: "123云盘", icon: "https://statics.123957.com/static-by-custom/favicon.ico" },
    { url: "https://www.alipan.com/drive/home", name: "阿里云盘", icon: "https://img.alicdn.com/imgextra/i1/O1CN01JDQCi21Dc8EfbRwvF_!!6000000000236-73-tps-64-64.ico" },
    { url: "https://pan.baidu.com/disk/main#/index?category=all", name: "百度网盘" },
    { url: "https://www.jianguoyun.com/#/", name: "坚果云" },
    { url: "https://up.woozooo.com/mydisk.php", name: "蓝奏云" },
    { url: "https://data.cstcloud.cn/", name: "首页 - 数据胶囊", icon: "https://data.cstcloud.cn/favicon.svg" },
    { url: "https://cloud.189.cn/web/main/file/folder/-11", name: "天翼云盘", icon: "https://cloud.dlife.cn/web/main/logo.ico" },
    { url: "https://photo.baidu.com/photo/web/home", name: "一刻相册", icon: "https://staticsns.cdn.bcebos.com/amis/2023-2/1676342310828/favicon.ico" },
    { url: "https://yun.139.com/w/#/index", name: "中国移动云盘", icon: "https://yun.139.com/w/static/img/LOGO.png" },
    { url: "https://mypikpak.com/drive/all", name: "PikPak", icon: "https://mypikpak.com/apple-touch-icon.png" },
    { url: "https://www.dropbox.com/home", name: "Dropbox", icon: "https://cfl.dropboxstatic.com/static/metaserver/static/images/favicon.ico" },
    { url: "https://photos.google.com/", name: "Google 相册" },
    { url: "https://drive.google.com/drive/my-drive", name: "Google硬盘" },
    { url: "https://mega.nz/fm/r3xmFDLJ", name: "MEGA", icon: "https://mega.nz/favicon.ico?v=3" },
    { url: "https://onedrive.live.com/?view=0", name: "OneDrive", icon: "https://onedrive.live.com/_layouts/15/images/odbfavicon.ico?rev=50" },
  ]},
  { name: "邮箱", links: [
    { url: "https://mail.qq.com/", name: "QQ邮箱", icon: "https://res.wx.qq.com/t/webmail/webmail/res/static/images/base/style/favicon/qqmail_favicon_32h.65f829f.png" },
  ]},
  { name: "论坛资讯社交", links: [
    { url: "https://60s-demo.viki.moe/", name: "60s 聚合信息流" },
    { url: "https://newsnow.busiyi.world/", name: "NewsNow", icon: "https://newsnow.busiyi.world/icon.svg" },
    { url: "https://sspai.com/", name: "少数派", icon: "https://cdn-static.sspai.com/favicon/sspai.ico" },
    { url: "https://weibo.com/", name: "微博" },
    { url: "https://m.weibo.cn/", name: "微博", icon: "https://h5.sinaimg.cn/m/weibo-lite/favicon-32.png" },
    { url: "https://x.com/", name: "X", icon: "https://abs.twimg.com/favicons/twitter.3.ico" },
    { url: "https://www.xiaohongshu.com/", name: "小红书", icon: "https://fe-video-qc.xhscdn.com/fe-platform/ed8fe781ce9e16c1bfac2cd962f0721edabe2e49.ico" },
    { url: "https://meta.appinn.net/", name: "小众软件", icon: "https://h2cdn.appinn.me/optimized/3X/a/0/a050bd00bdc1b1d3f1e77e315cd05dff88108ad7_2_32x32.png" },
    { url: "https://bbs.pcbeta.com/", name: "远景论坛", icon: "https://bbs.pcbeta.com/favicon-32x32.png" },
    { url: "https://discord.com/channels/@me", name: "Discord", icon: "https://discord.com/assets/favicon.ico" },
    { url: "https://hellogithub.com/", name: "HelloGitHub", icon: "https://hellogithub.com/favicon/favicon.svg" },
    { url: "https://www.itsk.com/", name: "IT天空" },
    { url: "https://www.instagram.com/", name: "Instagram", icon: "https://static.cdninstagram.com/rsrc.php/yr/r/rzWiSjZRxk5.webp" },
    { url: "https://linux.do/", name: "LINUX DO", icon: "https://cdn3.ldstatic.com/optimized/4X/c/c/d/ccd8c210609d498cbeb3d5201d4c259348447562_2_32x32.png" },
    { url: "https://ngabbs.com/", name: "NGA" },
    { url: "https://www.reddit.com/", name: "Reddit" },
    { url: "https://rutracker.org/forum/index.php", name: "RuTracker.org", icon: "https://rutracker.org/favicon-32x32.png" },
    { url: "https://www.v2ex.com/", name: "V2EX", icon: "https://www.v2ex.com/static/icon-192.png" },
    { url: "https://xdaforums.com/", name: "XDA Forums", icon: "https://xdaforums.com/data/assets/logo/favicon-32x32.png" },
  ]},
  { name: "视频音乐", links: [
    { url: "https://www.bilibili.com/", name: "哔哩哔哩", icon: "https://i0.hdslb.com/bfs/static/jinkela/long/images/favicon.ico" },
    { url: "https://www.douyin.com/", name: "抖音", icon: "https://p-pc-weboff.byteimg.com/tos-cn-i-9r5gewecjs/favicon.png" },
    { url: "https://www.tiktok.com/?lang=zh-Hans", name: "TikTok" },
    { url: "https://www.agedm.io/", name: "AGE动漫" },
    { url: "https://www.youtube.com/", name: "YouTube", icon: "https://www.youtube.com/s/desktop/cf14c559/img/favicon_32x32.png" },
    { url: "https://share.dmhy.org/", name: "動漫花園" },
    { url: "https://mikanani.me/", name: "Mikan", icon: "https://mikanani.me/images/favicon.ico?v=2" },
    { url: "https://vcb-s.com/", name: "VCB-Studio", icon: "https://vcb-s.com/wp-content/customRes/favicon@32.png" },
    { url: "https://open.spotify.com/", name: "Spotify", icon: "https://open.spotifycdn.com/cdn/images/favicon32.b64ecc03.png" },
    { url: "https://music.youtube.com/", name: "YouTube Music", icon: "https://music.youtube.com/img/favicon_32.png" },
  ]},
  { name: "漫画图片小说", links: [
    { url: "https://www.mangacopy.com/", name: "拷貝漫畫", icon: "https://s3.mangafunb.fun/static/free.ico" },
    { url: "https://www.kongfz.com/", name: "孔夫子旧书网", icon: "https://www.kongfz.com/favicon.ico" },
    { url: "https://shuyuan.yiove.com/", name: "Yiove 书源仓库 - 三千书源" },
    { url: "https://huaban.com/", name: "花瓣网", icon: "https://huaban.com/favicon.ico" },
    { url: "https://www.pinterest.com/", name: "Pinterest", icon: "https://s.pinimg.com/webapp/favicon_48x48-7470a30d.png" },
    { url: "https://www.artstation.com/", name: "ArtStation", icon: "https://www.artstation.com/assets/favicon.ico" },
    { url: "https://www.ggac.com/", name: "GGAC", icon: "https://cdn-prd.ggac.com/ggac/assets/image/favicon.png" },
    { url: "https://www.pixiv.net/", name: "pixiv", icon: "https://www.pixiv.net/favicon20250122.ico" },
    { url: "https://anilist.co/", name: "AniList", icon: "https://anilist.co/img/icons/favicon-32x32.png" },
  ]},
  { name: "工具", links: [
    { url: "https://metacubex.github.io/metacubexd/#/", name: "MetaCubeXD", icon: "https://metacubex.github.io/metacubexd/favicon.svg" },
    { url: "about:translations#src=detect&trg=zh-Hans", name: "Firefox 翻译" },
    { url: "https://fanyi.caiyunapp.com/", name: "彩云小译", icon: "https://www.caiyunapp.com/imgs/xiaoyilogo.png" },
    { url: "https://test.ustc.edu.cn/", name: "中国科学技术大学测速网站" },
    { url: "https://caniuse.com/", name: "Can I use", icon: "https://caniuse.com/img/favicon-128.png" },
    { url: "https://wiki.metacubex.one/", name: "mihomo", icon: "https://wiki.metacubex.one/assets/images.jpeg" },
    { url: "https://geoviewer.aloxaf.com/", name: "GeoSite Viewer | GeoSite 查看器", icon: "https://geoviewer.aloxaf.com/favicon.svg" },
    { url: "https://alternativeto.net/", name: "AlternativeTo", icon: "https://alternativeto.net/static/icons/a2/favicon-32x32.png" },
    { url: "https://www.cloudflare.com/cdn-cgi/trace" },
    { url: "https://www.aliyun.com/", name: "阿里云", icon: "https://img.alicdn.com/tfs/TB1_ZXuNcfpK1RjSZFOXXa6nFXa-32-32.ico" },
    { url: "https://console.cloud.tencent.com/", name: "腾讯云", icon: "https://cloudcache.tencent-cloud.com/qcloud/favicon.ico" },
    { url: "https://dash.cloudflare.com/", name: "Cloudflare", icon: "https://dash.cloudflare.com/favicon-32x32.png" },
    { url: "https://github.com/", name: "GitHub", icon: "https://github.githubassets.com/favicons/favicon.svg" },
    { url: "https://ppio.com/", name: "PPIO" },
    { url: "https://q.qq.com/", name: "QQ开放平台", icon: "https://qqminiapp.cdn-go.cn/qq-open-platform/b74dcdb6/favicon.svg" },
    { url: "https://www.virustotal.com/gui/home/upload", name: "VirusTotal - Home", icon: "https://www.virustotal.com/gui/images/favicon.svg" },
    { url: "https://poilv.github.io/" },
  ]},
];
